Repository AndreVarandas/chest-tracker-for-cr, pull requests merged in 2022-10, with the labels that each got.

#6 :tada: (birth) adds files
  .editorconfig
  .eslintrc.js
  .expo-shared/assets.json
  .gitignore
  .husky/pre-commit
  .prettierrc
  App.tsx
  app.json
  assets/adaptive-icon.png
  assets/favicon.png
  assets/icon.png
  assets/splash.png
  babel.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: hacktoberfest-accepted

#8 Create LICENSE
  LICENSE
Labels: hacktoberfest, hacktoberfest-accepted

#9 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: hacktoberfest, hacktoberfest-accepted

#13 Chore/update readme
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#14 Logo img
  README.md
  extra/cr-logo.png
  extra/optional-logo.png
Labels: hacktoberfest, hacktoberfest-accepted

#19 Fixing issue #16 - Add custom fonts
  App.tsx
  assets/fonts/Nunito-Regular.ttf
  assets/fonts/supercell-magic.ttf
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-accepted

#21 added image for social media previews
  extra/social-preview-image.jpg
Labels: hacktoberfest, hacktoberfest-accepted
